### ISSUE TITLE
[Epic] 랜딩페이지 제작

### ISSUE THREAD

**Issue by INKmin9** [withme58/front-end#10]
### 에픽 내용
- [ ] 랜딩페이지 컨테이너 제작
- [ ] '시작하기' 버튼 제작
- [ ] 페이지 레이아웃 짜놓기

### 예상 기간
- 3일

### 관련 사항
- 금요일까지이지만 빨리 해보겠어요 (근데 보통 이런건 안지켜짐 ㅇㅈ? ㅠㅠ)

**Comment by dhynxdhyn** [comment]
안 지켜짐 ㅇㅈ ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by INKmin9** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 과연 지켜질지..?
